# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-15 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20191214_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Image',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
