# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-15 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20191215_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to='images/'),
        ),
    ]
